[package]
name = "spawn-access-control"
version = "0.1.0"
edition = "2021"
description = "A WASM-based access-control token library for Web3 developers, providing a high-performance, secure, and customizable solution."
license = "MIT"
repository = "https://github.com/nzengi/spawn-access-control"
homepage = "https://github.com/nzengi/spawn-access-control"
readme = "README.md"
keywords = ["WASM", "access-control", "blockchain", "WebAssembly", "Rust"]
categories = ["cryptography", "web-programming"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"